Traceback (most recent call last):
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 507, in <module>
    pop_gen = population_generator(merger_file_1bh,merger_file_path,basePath,minN_values)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 49, in __init__
    self.all_merging_population,self.non_merging_population = self.generate_population(snap_list)
  File "/home/pranavsatheesh/host_galaxies/py_files/population_sort_by_mergers.py", line 114, in generate_population
    r_sep_non_merging = r_sep_valid_subhalos[subhalo_ids_non_merging]
IndexError: index 1229 is out of bounds for axis 0 with size 440
